version: '3'

services:
  node-app:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - react-js-app
      - redis
    volumes:
      - .:/spotifork

  react-js-app:
    build: ./frontend
    volumes:
      - .:/spotifork

  redis:
    image: redis
