version: '3'

services:
  node-app:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - react-js-app
      - redis
    volumes:
      - ./spotifork:/spotifork-volume

  react-js-app:
    build: ./frontend
    volumes:
      - ./spotifork:/spotifork-volume

  redis:
    image: redis

volumes:
  spotifork-volume: {}
