version: '3'

services:
  node-app:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - react-js-app
      - redis
    volumes:
      - ./build:/spotifork/server/build

  react-js-app:
    build: ./frontend
    volumes:
      - ./build:/spotifork/frontend/build

  redis:
    image: redis
